export enum ErrorCode {
  // Validation errors (400)
  VALIDATION_ERROR = "VALIDATION_ERROR",
  MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD",
  INVALID_SCHEMA = "INVALID_SCHEMA",
  INVALID_URL = "INVALID_URL",

  // Scraping errors (502)
  SCRAPING_FAILED = "SCRAPING_FAILED",
  BROWSER_LAUNCH_FAILED = "BROWSER_LAUNCH_FAILED",
  PAGE_LOAD_FAILED = "PAGE_LOAD_FAILED",
  PAGE_TIMEOUT = "PAGE_TIMEOUT",
  CONTENT_EXTRACTION_FAILED = "CONTENT_EXTRACTION_FAILED",

  // AI errors (503)
  AI_SERVICE_ERROR = "AI_SERVICE_ERROR",
  MODEL_ERROR = "MODEL_ERROR",
  TOKEN_LIMIT_EXCEEDED = "TOKEN_LIMIT_EXCEEDED",
  GENERATION_FAILED = "GENERATION_FAILED",

  // System errors (500)
  INTERNAL_ERROR = "INTERNAL_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
}
